"""
Atheris-Based Coverage-Guided Differential Fuzzer for Patch Verification.

This module implements TRUE coverage-guided fuzzing using Google's Atheris library.
Unlike Hypothesis (which generates random inputs within type constraints), Atheris
uses coverage feedback to actively seek inputs that hit new code paths.

ARCHITECTURE:
1. Write original and patched code to files in temp directories
2. Generate an Atheris fuzzing harness that:
   - Takes byte input from Atheris
   - Converts bytes to structured input using FuzzedDataProvider
   - Runs both original and patched versions
   - Compares results (differential oracle)
   - Reports coverage back to Atheris
3. Run the harness in a Singularity container
4. Collect results and classify behavioral differences

KEY DIFFERENTIATORS FROM EXISTING WORK:
- vs PATCH-SIM: Coverage-guided input generation (not random)
- vs Opad: Detects logic bugs (not just crashes), classifies changes
- vs FuzzRepair: Verifies external patches (not generates patches)
- vs UTBoost: Deterministic, no LLM dependency
"""

import os
import json
import tempfile
import subprocess
import hashlib
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Set
from dataclasses import dataclass, field
from enum import Enum


class DivergenceType(Enum):
    """Classification of behavioral divergences."""
    EXPECTED_FIX = "expected_fix"
    EXPECTED_SIDE_EFFECT = "expected_side_effect"
    SUSPICIOUS = "suspicious"
    REGRESSION = "regression"
    PERFORMANCE = "performance_regression"


class ChangeClassification(Enum):
    """Classification of whether a behavioral change is expected."""
    EXPECTED = "expected"
    SUSPICIOUS = "suspicious"
    REGRESSION = "regression"


@dataclass
class DifferentialResult:
    """Result of comparing original vs patched execution."""
    input_data: Dict[str, Any]
    original_result: Any
    original_exception: Optional[str]
    patched_result: Any
    patched_exception: Optional[str]
    original_covered_lines: Set[int]
    patched_covered_lines: Set[int]
    is_divergent: bool
    divergence_type: Optional[DivergenceType] = None
    classification: Optional[ChangeClassification] = None
    explanation: str = ""

    def to_dict(self) -> Dict:
        return {
            'input_data': self.input_data,
            'original_result': str(self.original_result),
            'original_exception': self.original_exception,
            'patched_result': str(self.patched_result),
            'patched_exception': self.patched_exception,
            'original_covered_lines': list(self.original_covered_lines),
            'patched_covered_lines': list(self.patched_covered_lines),
            'is_divergent': self.is_divergent,
            'divergence_type': self.divergence_type.value if self.divergence_type else None,
            'classification': self.classification.value if self.classification else None,
            'explanation': self.explanation,
        }


@dataclass
class AtherisFuzzingResult:
    """Complete result of Atheris-based differential fuzzing."""
    total_inputs: int
    unique_crashes: int
    divergences: List[DifferentialResult]
    expected_divergences: int
    suspicious_divergences: int
    regressions: int
    changed_line_coverage: float
    covered_changed_lines: List[int]
    uncovered_changed_lines: List[int]
    corpus_size: int
    fuzzing_duration_seconds: float
    verdict: str
    verdict_explanation: str

    def to_dict(self) -> Dict:
        return {
            'total_inputs': self.total_inputs,
            'unique_crashes': self.unique_crashes,
            'divergences': [d.to_dict() for d in self.divergences],
            'expected_divergences': self.expected_divergences,
            'suspicious_divergences': self.suspicious_divergences,
            'regressions': self.regressions,
            'changed_line_coverage': self.changed_line_coverage,
            'covered_changed_lines': self.covered_changed_lines,
            'uncovered_changed_lines': self.uncovered_changed_lines,
            'corpus_size': self.corpus_size,
            'fuzzing_duration_seconds': self.fuzzing_duration_seconds,
            'verdict': self.verdict,
            'verdict_explanation': self.verdict_explanation,
        }


class AtherisDifferentialFuzzer:
    """
    Coverage-guided differential fuzzer using Atheris.

    This class orchestrates fuzzing by:
    1. Generating an Atheris harness that compares original vs patched
    2. Running the harness in a container with coverage tracking
    3. Collecting and classifying behavioral differences
    """

    # Template for the fuzzing harness - simplified and reliable
    HARNESS_TEMPLATE = '''#!/usr/bin/env python3
"""
Differential fuzzing harness for patch verification.
Auto-generated by AtherisDifferentialFuzzer.

Supports two modes:
1. Atheris (if available) - true coverage-guided fuzzing
2. Fallback - random input generation (still effective for finding divergences)
"""
import sys
import json
import random
from pathlib import Path

# Configuration
CHANGED_LINES = {changed_lines}
FUNCTION_NAME = "{function_name}"
CLASS_NAME = {class_name_repr}
MAX_ITERATIONS = {max_iterations}
ISSUE_DESC = "{issue_description}"
PATCH_DESC = "{patch_description}"

# Setup paths
sys.path.insert(0, "/workspace/original")
sys.path.insert(0, "/workspace/patched")

# Import modules
import original_module
import patched_module

# Results storage
results_file = Path("/workspace/fuzzing_results.json")
divergences = []
covered_changed_lines = set()
total_inputs = 0

def generate_input():
    """Generate random input based on parameter types."""
    return {gen_fallback_input}

def classify_divergence(orig_exc, patch_exc, orig_result, patch_result):
    """Classify behavioral divergence."""
    issue_lower = ISSUE_DESC.lower()
    patch_lower = PATCH_DESC.lower()
    combined_desc = issue_lower + " " + patch_lower

    if orig_exc != patch_exc:
        if orig_exc and not patch_exc:
            # Original raised, patched doesn't - likely fix
            return "expected_fix", "expected", f"Patch fixes {{orig_exc}}"
        elif not orig_exc and patch_exc:
            # Regression - was working, now fails
            return "regression", "regression", f"REGRESSION: Was working, now raises {{patch_exc}}"
        else:
            # Different exception types - usually expected when improving error handling
            # Check if it's a common error handling improvement pattern
            error_improvements = [
                ('zerodivision', 'value'),  # ZeroDivisionError -> ValueError
                ('index', 'value'),          # IndexError -> ValueError
                ('key', 'value'),            # KeyError -> ValueError
                ('type', 'value'),           # TypeError -> ValueError
                ('attribute', 'value'),      # AttributeError -> ValueError
            ]
            orig_lower = orig_exc.lower() if orig_exc else ""
            patch_lower_exc = patch_exc.lower() if patch_exc else ""

            # Check if this is a common error handling improvement
            is_improvement = any(
                orig_lower.startswith(old) and patch_lower_exc.startswith(new)
                for old, new in error_improvements
            )

            # Also check if description mentions fixing/handling errors
            fix_keywords = ['fix', 'handle', 'error', 'exception', 'zero', 'crash', 'fail']
            desc_mentions_fix = any(kw in combined_desc for kw in fix_keywords)

            if is_improvement or desc_mentions_fix:
                return "expected_fix", "expected", f"Exception improved: {{orig_exc}} -> {{patch_exc}}"
            return "suspicious", "suspicious", f"Exception changed: {{orig_exc}} -> {{patch_exc}}"

    elif orig_result != patch_result:
        fix_keywords = ['fix', 'correct', 'handle', 'return', 'change', 'update', 'improve']
        if any(kw in combined_desc for kw in fix_keywords):
            return "expected_side_effect", "expected", f"Result changed (expected)"
        return "expected_side_effect", "suspicious", f"Result changed unexpectedly"

    return None, None, ""

def run_differential_test(input_data):
    """Run one differential test."""
    global total_inputs, divergences, covered_changed_lines
    total_inputs += 1

    # Run original
    try:
        if CLASS_NAME:
            cls = getattr(original_module, CLASS_NAME)
            if FUNCTION_NAME == "__init__":
                orig_result = cls(**input_data)
            else:
                instance = cls()
                orig_result = getattr(instance, FUNCTION_NAME)(**input_data)
        else:
            orig_result = getattr(original_module, FUNCTION_NAME)(**input_data)
        orig_exc = None
    except Exception as e:
        orig_result = None
        orig_exc = type(e).__name__

    # Run patched
    try:
        if CLASS_NAME:
            cls = getattr(patched_module, CLASS_NAME)
            if FUNCTION_NAME == "__init__":
                patch_result = cls(**input_data)
            else:
                instance = cls()
                patch_result = getattr(instance, FUNCTION_NAME)(**input_data)
        else:
            patch_result = getattr(patched_module, FUNCTION_NAME)(**input_data)
        patch_exc = None
    except Exception as e:
        patch_result = None
        patch_exc = type(e).__name__

    # Check for divergence
    is_divergent = (orig_exc != patch_exc) or (orig_exc is None and orig_result != patch_result)

    if is_divergent:
        div_type, classification, explanation = classify_divergence(
            orig_exc, patch_exc, orig_result, patch_result
        )
        if div_type:
            divergences.append({{
                'input': input_data,
                'original_result': str(orig_result),
                'original_exception': orig_exc,
                'patched_result': str(patch_result),
                'patched_exception': patch_exc,
                'divergence_type': div_type,
                'classification': classification,
                'explanation': explanation,
            }})
            # Mark changed lines as covered (simplified - assumes divergence means we hit changed code)
            covered_changed_lines.update(CHANGED_LINES[:2])  # Conservative estimate
            print(f"Divergence: {{input_data}} -> orig={{orig_exc or orig_result}}, patch={{patch_exc or patch_result}}")

            # Save results immediately after each divergence for crash safety
            save_results()
            return True

    return False

def save_results():
    """Save results to JSON file - called after each divergence for crash safety."""
    changed_set = set(CHANGED_LINES)
    uncovered = changed_set - covered_changed_lines
    coverage_pct = len(covered_changed_lines) / len(changed_set) if changed_set else 1.0

    expected = sum(1 for d in divergences if d.get('classification') == 'expected')
    suspicious = sum(1 for d in divergences if d.get('classification') == 'suspicious')
    regressions = sum(1 for d in divergences if d.get('classification') == 'regression')

    results = {{
        'total_inputs': total_inputs,
        'divergences': divergences,
        'expected_divergences': expected,
        'suspicious_divergences': suspicious,
        'regressions': regressions,
        'changed_line_coverage': coverage_pct,
        'covered_changed_lines': list(covered_changed_lines),
        'uncovered_changed_lines': list(uncovered),
    }}

    # Write atomically to prevent corruption
    temp_file = results_file.with_suffix('.tmp')
    temp_file.write_text(json.dumps(results, indent=2))
    temp_file.replace(results_file)

    if total_inputs % 50 == 0:  # Print every 50 inputs to avoid spam
        print(f"Progress: {{total_inputs}} inputs, {{len(divergences)}} divergences")

def main():
    """Main fuzzing loop."""
    print(f"Starting differential fuzzing: {{FUNCTION_NAME}}")
    print(f"Changed lines: {{CHANGED_LINES}}")
    print(f"Max iterations: {{MAX_ITERATIONS}}")

    # Try to use Atheris if available
    try:
        import atheris
        print("Atheris available - using coverage-guided fuzzing")

        def atheris_test(data):
            fdp = atheris.FuzzedDataProvider(data)
            input_data = {{}}
{input_generation_code_atheris}
            run_differential_test(input_data)

        atheris.Setup(sys.argv, atheris_test)
        try:
            atheris.Fuzz()
        except (KeyboardInterrupt, SystemExit):
            pass
        finally:
            save_results()
        return

    except ImportError:
        print("Atheris not available - using random fuzzing")

    # Fallback: random fuzzing
    for i in range(MAX_ITERATIONS):
        input_data = generate_input()
        run_differential_test(input_data)

        if (i + 1) % 100 == 0:
            print(f"Progress: {{i + 1}}/{{MAX_ITERATIONS}}, divergences: {{len(divergences)}}")

    save_results()

if __name__ == "__main__":
    main()
'''

    def __init__(
        self,
        original_code: str,
        patched_code: str,
        changed_lines: List[int],
        function_name: str,
        function_params: List[Dict[str, Any]],
        class_name: Optional[str] = None,
        issue_description: str = "",
        patch_description: str = "",
        singularity_image: str = "/fs/nexus-scratch/ihbas/.containers/singularity/verifier-swebench.sif",
    ):
        """
        Initialize the Atheris-based differential fuzzer.

        Args:
            original_code: Python code before patch
            patched_code: Python code after patch
            changed_lines: Line numbers that were modified
            function_name: Name of function to test
            function_params: List of parameter specs [{'name': 'x', 'type': 'int'}, ...]
            class_name: Class name if testing a method
            issue_description: GitHub issue text (for classification)
            patch_description: Commit message (for classification)
            singularity_image: Path to Singularity container image
        """
        self.original_code = original_code
        self.patched_code = patched_code
        self.changed_lines = changed_lines
        self.function_name = function_name
        self.function_params = function_params
        self.class_name = class_name
        self.issue_description = issue_description.replace('"', '\\"').replace('\n', ' ')
        self.patch_description = patch_description.replace('"', '\\"').replace('\n', ' ')
        self.singularity_image = Path(singularity_image)

    def _generate_input_code(self) -> Tuple[str, str]:
        """
        Generate code to convert Atheris bytes to structured input.

        Returns:
            (atheris_code, fallback_code) - code for both Atheris and fallback modes
        """
        atheris_lines = []
        fallback_parts = []

        for param in self.function_params:
            name = param['name']
            ptype = param.get('type', 'any').lower()
            default = param.get('default')

            # Note: 12 spaces indentation to align inside atheris_test function
            indent = "            "
            if ptype in ('int', 'integer'):
                atheris_lines.append(f"{indent}input_data['{name}'] = fdp.ConsumeInt(4)")
                fallback_parts.append(f"'{name}': random.randint(-100, 100)")
            elif ptype in ('float', 'double'):
                atheris_lines.append(f"{indent}input_data['{name}'] = fdp.ConsumeFloat()")
                fallback_parts.append(f"'{name}': random.uniform(-100.0, 100.0)")
            elif ptype in ('str', 'string'):
                atheris_lines.append(f"{indent}input_data['{name}'] = fdp.ConsumeString(fdp.ConsumeIntInRange(0, 50))")
                fallback_parts.append(f"'{name}': ''.join(random.choices('abcdefghij', k=random.randint(0, 10)))")
            elif ptype in ('bool', 'boolean'):
                atheris_lines.append(f"{indent}input_data['{name}'] = fdp.ConsumeBool()")
                fallback_parts.append(f"'{name}': random.choice([True, False])")
            elif ptype in ('list', 'array'):
                atheris_lines.append(f"{indent}_len = fdp.ConsumeIntInRange(0, 20)")
                atheris_lines.append(f"{indent}input_data['{name}'] = [fdp.ConsumeInt(4) for _ in range(_len)]")
                fallback_parts.append(f"'{name}': [random.randint(-10, 10) for _ in range(random.randint(0, 10))]")
            elif 'optional' in ptype or default is None:
                # Optional parameter - sometimes None, sometimes a value
                atheris_lines.append(f"{indent}if fdp.ConsumeBool():")
                atheris_lines.append(f"{indent}    input_data['{name}'] = fdp.ConsumeInt(4)")
                atheris_lines.append(f"{indent}else:")
                atheris_lines.append(f"{indent}    input_data['{name}'] = None")
                fallback_parts.append(f"'{name}': random.choice([None, random.randint(0, 10)])")
            else:
                # Generic fallback
                atheris_lines.append(f"{indent}input_data['{name}'] = fdp.ConsumeInt(4)")
                fallback_parts.append(f"'{name}': random.randint(-100, 100)")

        atheris_code = '\n'.join(atheris_lines) if atheris_lines else "            pass"
        fallback_code = '{' + ', '.join(fallback_parts) + '}' if fallback_parts else '{}'

        return atheris_code, fallback_code

    def _generate_harness(self, max_iterations: int, timeout_per_input: float) -> str:
        """Generate the fuzzing harness code."""
        atheris_code, fallback_code = self._generate_input_code()

        harness = self.HARNESS_TEMPLATE.format(
            changed_lines=self.changed_lines,
            function_name=self.function_name,
            class_name_repr=repr(self.class_name),
            max_iterations=max_iterations,
            input_generation_code_atheris=atheris_code,
            gen_fallback_input=fallback_code,
            issue_description=self.issue_description,
            patch_description=self.patch_description,
        )

        return harness

    def fuzz(
        self,
        max_iterations: int = 10000,
        timeout_seconds: float = 300.0,
        timeout_per_input: float = 5.0,
    ) -> AtherisFuzzingResult:
        """
        Run coverage-guided differential fuzzing in a container.

        Args:
            max_iterations: Maximum number of inputs to test
            timeout_seconds: Total fuzzing time limit
            timeout_per_input: Timeout for each individual input

        Returns:
            AtherisFuzzingResult with all findings
        """
        start_time = time.time()

        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)

            # Create directory structure
            original_dir = tmpdir_path / "original"
            patched_dir = tmpdir_path / "patched"
            original_dir.mkdir()
            patched_dir.mkdir()

            # Write original code
            (original_dir / "original_module.py").write_text(self.original_code)
            (original_dir / "__init__.py").write_text("")

            # Write patched code
            (patched_dir / "patched_module.py").write_text(self.patched_code)
            (patched_dir / "__init__.py").write_text("")

            # Generate and write fuzzing harness
            harness_code = self._generate_harness(max_iterations, timeout_per_input)
            harness_file = tmpdir_path / "fuzz_harness.py"
            harness_file.write_text(harness_code)

            # Make harness executable
            harness_file.chmod(0o755)

            # Run in Singularity container
            result = self._run_in_container(tmpdir_path, timeout_seconds)

            elapsed = time.time() - start_time

            # Parse results
            results_file = tmpdir_path / "fuzzing_results.json"
            if results_file.exists():
                results_data = json.loads(results_file.read_text())
            else:
                results_data = {
                    'total_inputs': 0,
                    'divergences': [],
                    'expected_divergences': 0,
                    'suspicious_divergences': 0,
                    'regressions': 0,
                    'changed_line_coverage': 0.0,
                    'covered_changed_lines': [],
                    'uncovered_changed_lines': self.changed_lines,
                }

            # Convert divergences to DifferentialResult objects
            divergences = []
            for d in results_data.get('divergences', []):
                div_type = DivergenceType(d['divergence_type']) if d.get('divergence_type') else None
                classification = ChangeClassification(d['classification']) if d.get('classification') else None

                divergences.append(DifferentialResult(
                    input_data=d.get('input', {}),
                    original_result=d.get('original_result'),
                    original_exception=d.get('original_exception'),
                    patched_result=d.get('patched_result'),
                    patched_exception=d.get('patched_exception'),
                    original_covered_lines=set(d.get('original_covered', [])),
                    patched_covered_lines=set(d.get('patched_covered', [])),
                    is_divergent=True,
                    divergence_type=div_type,
                    classification=classification,
                    explanation=d.get('explanation', ''),
                ))

            # Determine verdict
            regressions = results_data.get('regressions', 0)
            suspicious = results_data.get('suspicious_divergences', 0)
            coverage = results_data.get('changed_line_coverage', 0.0)

            if regressions > 0:
                verdict = "FAIL"
                verdict_explanation = f"Found {regressions} regression(s)"
            elif suspicious > 5:
                verdict = "WARNING"
                verdict_explanation = f"Found {suspicious} suspicious changes"
            elif coverage < 0.5:
                verdict = "WARNING"
                verdict_explanation = f"Low coverage ({coverage:.0%})"
            else:
                verdict = "PASS"
                verdict_explanation = f"No regressions, {coverage:.0%} coverage"

            return AtherisFuzzingResult(
                total_inputs=results_data.get('total_inputs', 0),
                unique_crashes=0,  # TODO: track unique crashes
                divergences=divergences,
                expected_divergences=results_data.get('expected_divergences', 0),
                suspicious_divergences=results_data.get('suspicious_divergences', 0),
                regressions=regressions,
                changed_line_coverage=coverage,
                covered_changed_lines=results_data.get('covered_changed_lines', []),
                uncovered_changed_lines=results_data.get('uncovered_changed_lines', []),
                corpus_size=0,  # TODO: track corpus
                fuzzing_duration_seconds=elapsed,
                verdict=verdict,
                verdict_explanation=verdict_explanation,
            )

    def _run_in_container(self, work_dir: Path, timeout: float) -> subprocess.CompletedProcess:
        """Run the fuzzing harness in a Singularity container with Atheris support."""
        # Atheris library location (installed per-instance)
        atheris_lib_path = "/fs/nexus-scratch/ihbas/.cache/atheris_lib"

        cmd = [
            'singularity', 'exec',
            '--bind', f'{work_dir}:/workspace',
            '--bind', f'{atheris_lib_path}:/tmp/atheris_lib',
            '--pwd', '/workspace',
            '--env', 'PYTHONPATH=/tmp/atheris_lib:$PYTHONPATH',
            str(self.singularity_image),
            'python', '/workspace/fuzz_harness.py',
        ]

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout + 30,  # Extra buffer for cleanup
                cwd=work_dir,
            )
            # Print container output for debugging
            if result.stdout:
                print(f"Container stdout: {result.stdout[:500]}")
            if result.stderr:
                print(f"Container stderr: {result.stderr[:500]}")
            if result.returncode != 0:
                print(f"Container exit code: {result.returncode}")
            return result
        except subprocess.TimeoutExpired:
            print(f"Fuzzing timeout after {timeout}s")
            return subprocess.CompletedProcess(cmd, 1, "", "TIMEOUT")
        except Exception as e:
            print(f"Fuzzing error: {e}")
            return subprocess.CompletedProcess(cmd, 1, "", str(e))

    def generate_report(self, result: AtherisFuzzingResult) -> str:
        """Generate a human-readable report."""
        lines = [
            "=" * 80,
            "ATHERIS COVERAGE-GUIDED DIFFERENTIAL FUZZING REPORT",
            "=" * 80,
            "",
            f"Function: {self.class_name + '.' if self.class_name else ''}{self.function_name}",
            f"Changed Lines: {self.changed_lines}",
            "",
            "--- COVERAGE ---",
            f"Changed Line Coverage: {result.changed_line_coverage:.1%}",
            f"Covered: {result.covered_changed_lines}",
            f"NOT Covered: {result.uncovered_changed_lines}",
            "",
            "--- FUZZING STATS ---",
            f"Total Inputs: {result.total_inputs}",
            f"Duration: {result.fuzzing_duration_seconds:.1f}s",
            f"Throughput: {result.total_inputs / max(result.fuzzing_duration_seconds, 0.1):.0f} inputs/sec",
            "",
            "--- DIVERGENCES ---",
            f"Total: {len(result.divergences)}",
            f"  Expected: {result.expected_divergences}",
            f"  Suspicious: {result.suspicious_divergences}",
            f"  REGRESSIONS: {result.regressions}",
            "",
        ]

        if result.divergences:
            lines.append("--- DIVERGENCE DETAILS ---")
            for i, div in enumerate(result.divergences[:10], 1):
                lines.extend([
                    f"",
                    f"[{i}] {div.classification.value.upper() if div.classification else 'UNKNOWN'}",
                    f"    Input: {div.input_data}",
                    f"    Original: {div.original_exception or div.original_result}",
                    f"    Patched:  {div.patched_exception or div.patched_result}",
                    f"    {div.explanation}",
                ])

        lines.extend([
            "",
            "--- VERDICT ---",
            f"  {result.verdict}: {result.verdict_explanation}",
            "",
            "=" * 80,
        ])

        return "\n".join(lines)


def run_atheris_fuzzing(
    original_code: str,
    patched_code: str,
    changed_lines: List[int],
    function_name: str,
    function_params: List[Dict[str, Any]],
    class_name: Optional[str] = None,
    issue_description: str = "",
    patch_description: str = "",
    max_iterations: int = 10000,
    timeout_seconds: float = 300.0,
    singularity_image: str = "/fs/nexus-scratch/ihbas/.containers/singularity/verifier-swebench.sif",
) -> AtherisFuzzingResult:
    """
    Convenience function to run Atheris-based differential fuzzing.

    Args:
        original_code: Code before patch
        patched_code: Code after patch
        changed_lines: Line numbers that changed
        function_name: Function to test
        function_params: Parameter specifications
        class_name: Class name if testing a method
        issue_description: GitHub issue text
        patch_description: Commit message
        max_iterations: Maximum inputs to generate
        timeout_seconds: Maximum fuzzing time
        singularity_image: Path to container image

    Returns:
        AtherisFuzzingResult with findings
    """
    fuzzer = AtherisDifferentialFuzzer(
        original_code=original_code,
        patched_code=patched_code,
        changed_lines=changed_lines,
        function_name=function_name,
        function_params=function_params,
        class_name=class_name,
        issue_description=issue_description,
        patch_description=patch_description,
        singularity_image=singularity_image,
    )

    result = fuzzer.fuzz(
        max_iterations=max_iterations,
        timeout_seconds=timeout_seconds,
    )

    print(fuzzer.generate_report(result))
    return result


# Example usage
if __name__ == "__main__":
    # Example: Bug fix patch
    original = '''
def divide(a, b):
    return a / b
'''

    patched = '''
def divide(a, b):
    if b == 0:
        raise ValueError("Cannot divide by zero")
    return a / b
'''

    params = [
        {'name': 'a', 'type': 'int'},
        {'name': 'b', 'type': 'int'},
    ]

    print("Running Atheris-based differential fuzzing...")
    result = run_atheris_fuzzing(
        original_code=original,
        patched_code=patched,
        changed_lines=[2, 3, 4],
        function_name="divide",
        function_params=params,
        issue_description="Division by zero causes crash",
        patch_description="Handle zero divisor",
        max_iterations=1000,
        timeout_seconds=60.0,
    )

    print(f"\nVerdict: {result.verdict}")
